namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string
    CLERK_SECRET_KEY: string
    NEXT_PUBLIC_CONVEX_URL: string
    POLAR_ACCESS_TOKEN: string
    NEXT_PUBLIC_POLAR_ORGANISATION_ID: string
    POLAR_WEBHOOK_SECRET: string
    CONVEX_DEPLOYMENT_URL: string
    CONVEX_DEPLOY_KEY: string
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string
    STRIPE_SECRET_KEY: string
    RAZORPAY_KEY_ID: string
    RAZORPAY_KEY_SECRET: string
    NEXT_PUBLIC_SUPABASE_URL: string
    NEXT_PUBLIC_SUPABASE_ANON_KEY: string
  }
}
